ALTER TABLE sites ADD COLUMN installazione_cantiere_pct INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sites ADD COLUMN rabotage_pct INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sites ADD COLUMN pozzi_pompaggio_pct INTEGER NOT NULL DEFAULT 0;
