ALTER TABLE depots ADD COLUMN city VARCHAR(120);
ALTER TABLE depots ADD COLUMN zip VARCHAR(20);
ALTER TABLE depots ADD COLUMN province VARCHAR(120);
ALTER TABLE depots ADD COLUMN country VARCHAR(120);
ALTER TABLE depots ADD COLUMN lat FLOAT;
ALTER TABLE depots ADD COLUMN lng FLOAT;
